# Generated by Django 5.0.7 on 2025-11-01 23:30

import os
from django.db import migrations

def create_google_social_app(apps, schema_editor):
    """Create the Google SocialApp for django-allauth."""
    Site = apps.get_model('sites', 'Site')
    SocialApp = apps.get_model('socialaccount', 'SocialApp')

    # Get the current site
    # In a fresh migration, the default site (pk=1) should exist.
    try:
        site = Site.objects.get(pk=os.environ.get('SITE_ID', 1))
    except Site.DoesNotExist:
        # If it doesn't exist for some reason, create it.
        site = Site.objects.create(
            domain=os.environ.get('DOMAIN', 'example.com'),
            name=os.environ.get('SITE_NAME', 'example')
        )

    # Get Google credentials from environment variables
    client_id = os.environ.get('GOOGLE_CLIENT_ID')
    secret = os.environ.get('GOOGLE_CLIENT_SECRET')

    # Only proceed if the credentials are set
    if client_id and secret:
        # Check if the SocialApp already exists to avoid duplicates
        if not SocialApp.objects.filter(provider='google').exists():
            google_app = SocialApp.objects.create(
                provider='google',
                name='Google',
                client_id=client_id,
                secret=secret,
            )
            google_app.sites.add(site)


def remove_google_social_app(apps, schema_editor):
    """Remove the Google SocialApp."""
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    SocialApp.objects.filter(provider='google').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('socialaccount', '0001_initial'), # Dependency on allauth's migration
        ('sites', '0001_initial'),       # Dependency on the sites framework
    ]

    operations = [
        migrations.RunPython(create_google_social_app, remove_google_social_app),
    ]
