# Generated by Django 5.2.7 on 2025-12-09 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_profile_business_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('selected_services', models.JSONField()),
                ('price_estimate_min_naira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_estimate_max_naira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_estimate_min_dollar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_estimate_max_dollar', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.CharField(blank=True, max_length=200)),
                ('additional_info', models.TextField(blank=True)),
                ('contact_method', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
