# Generated by Django 5.2.7 on 2025-12-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_quotation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Pending', 'Pending'), ('Reviewed', 'Reviewed'), ('Paid', 'Paid'), ('In Progress', 'In Progress'), ('Done', 'Done'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
