from django.urls import path
from .views import (
    health_check,
    membership_billing,
    profile,
    signin,
    signup,
    chat,
    community,
    dashboard_data,
    submit_quotation,
    get_quotations,
    download_quotation_pdf,
    get_quotation_detail,
    update_quotation,
    list_all_quotations,
    update_quotation_status,
    list_completed_works,
    create_report,
    list_reports,
    update_report_status,
    community_posts,
    community_post_detail,
    post_comments,
    comment_detail,
    toggle_post_like,
    toggle_comment_like,
    get_notifications,
    mark_notification_read,
    mark_notification_read,
    mark_all_notifications_read,
    get_user_details,
    react_to_message,
)

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('auth/me/', get_user_details, name='get_user_details'),
    path('membership-billing/', membership_billing, name='membership_billing'),
    path('profile/', profile, name='profile'),
    path('quotations/submit/', submit_quotation, name='submit_quotation'),
    path('quotations/', get_quotations, name='get_quotations'),
    path('quotations/<str:quotation_id>/download/', download_quotation_pdf, name='download_quotation_pdf'),
    path('quotations/<str:quotation_id>/', get_quotation_detail, name='get_quotation_detail'),
    path('quotations/<str:quotation_id>/update/', update_quotation, name='update_quotation'),
    path('admin/quotations/', list_all_quotations, name='list_all_quotations'),
    path('admin/quotations/<str:quotation_id>/status/', update_quotation_status, name='update_quotation_status'),
    path('works/', list_completed_works, name='list_completed_works'),
    path('reports/create/', create_report, name='create_report'),
    path('admin/reports/', list_reports, name='list_reports'),
    path('admin/reports/<int:report_id>/status/', update_report_status, name='update_report_status'),
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('chat/', chat, name='chat'),
    path('chat/messages/<int:message_id>/react/', react_to_message, name='react_to_message'),
    path('community/', community, name='community'),
    path('dashboard/', dashboard_data, name='dashboard'),
    # Community Posts
    path('community/posts/', community_posts, name='community_posts'),
    path('community/posts/<int:post_id>/', community_post_detail, name='community_post_detail'),
    path('community/posts/<int:post_id>/comments/', post_comments, name='post_comments'),
    path('community/posts/<int:post_id>/like/', toggle_post_like, name='toggle_post_like'),
    path('community/comments/<int:comment_id>/', comment_detail, name='comment_detail'),
    path('community/comments/<int:comment_id>/like/', toggle_comment_like, name='toggle_comment_like'),
    # Notifications
    path('notifications/', get_notifications, name='get_notifications'),
    path('notifications/<int:notification_id>/read/', mark_notification_read, name='mark_notification_read'),
    path('notifications/read-all/', mark_all_notifications_read, name='mark_all_notifications_read'),
]