from django.urls import path
from .views import (
    health_check,
    membership_billing,
    profile,
    signin,
    signup,
    chat,
    community,
    dashboard_data,
    submit_quotation,
    get_quotations,
    download_quotation_pdf,
    get_quotation_detail,
    update_quotation,
    list_all_quotations,
    update_quotation_status,
    list_completed_works,
    create_report,
    list_reports,
    update_report_status,
)

urlpatterns = [
    path('health/', health_check, name='health_check'),
    path('membership-billing/', membership_billing, name='membership_billing'),
    path('profile/', profile, name='profile'),
    path('quotations/submit/', submit_quotation, name='submit_quotation'),
    path('quotations/', get_quotations, name='get_quotations'),
    path('quotations/<str:quotation_id>/download/', download_quotation_pdf, name='download_quotation_pdf'),
    path('quotations/<str:quotation_id>/', get_quotation_detail, name='get_quotation_detail'),
    path('quotations/<str:quotation_id>/update/', update_quotation, name='update_quotation'),
    path('admin/quotations/', list_all_quotations, name='list_all_quotations'),
    path('admin/quotations/<str:quotation_id>/status/', update_quotation_status, name='update_quotation_status'),
    path('works/', list_completed_works, name='list_completed_works'),
    path('reports/create/', create_report, name='create_report'),
    path('admin/reports/', list_reports, name='list_reports'),
    path('admin/reports/<int:report_id>/status/', update_report_status, name='update_report_status'),
    path('signin/', signin, name='signin'),
    path('signup/', signup, name='signup'),
    path('chat/', chat, name='chat'),
    path('community/', community, name='community'),
    path('dashboard/', dashboard_data, name='dashboard'),
]